DATA		SEGMENT
ARRAY		DB	4 DUP ('?')
DATA		ENDS
CODE		SEGMENT
		ASSUME	CS: CODE, DS: DATA
START:		MOV	AX, DATA
		MOV	DS, AX
		MOV	ARRAY, 0		;第一个元素清零
		MOV	ARRAY+1, 0		;第二个元素清零
		MOV	ARRAY+2, 0		;第三个元素清零
		MOV	ARRAY+3, 0		;第四个元素清零
		MOV	AX, 4C00H
		INT	21H
CODE		ENDS
		END	START
